version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: medical_tests
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/medical_tests
    ports:
      - "3000:3000"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
