version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: medical_tests
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
  api:
    image: ruby:latest
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./back:/app
      - bundle_data_back:/usr/local/bundle
      - ./back/data:/app/data
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c 'gem install bundler && bundle install && ruby server.rb'
    container_name: relabs-api

volumes:
  db_data:

networks:
  backend:
